name: Build Automator APK
on:
  workflow_dispatch:
  push:
    paths:
      - 'AutomatorFull.zip'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare project
        run: |
          ls -la
          if [ -f AutomatorFull.zip ]; then unzip -o AutomatorFull.zip; fi
          if [ -f AutomatorFull/settings.gradle.kts ]; then echo "BUILD_DIR=AutomatorFull" >> $GITHUB_ENV; else echo "BUILD_DIR=." >> $GITHUB_ENV; fi
          echo "Using BUILD_DIR=$BUILD_DIR"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          build-root-directory: ${{ env.BUILD_DIR }}
          arguments: :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ${{ env.BUILD_DIR }}/app/build/outputs/apk/debug/app-debug.apk
